title   Arch Manager Recovery (%ARCH%, UEFI)
sort-key 01
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet loglevel=3 rd.systemd.show_status=false systemd.show_status=false rd.udev.log_level=3 udev.log_level=3 arch_manager_usb=1
